export const ClassData = [
    {
        id: 1,
        type: "YL-Starters",
        time: "7:30 - 9:00 AM",
        day: "Sat & Sun",
        ageGroup: "5 to 6 years",
        backgroundColor: "bg-red-400",
        textColor: "text-red-400",
        delay: 0.2,
    },
    {
        id: 2,
        type: "Pre YL-1",
        time: "7:30 - 9:00 AM",
        day: "Sat & Sun",
        ageGroup: "6 to 8 years",
        backgroundColor: "bg-teal-400",
        textColor: "text-teal-400",
        delay: 0.5,
    },
    {
        id: 3,
        type: "YL-1",
        time: "6:00 - 7:00 PM",
        day: "Mon - Thu",
        ageGroup: "7 to 9 years",
        backgroundColor: "bg-cyan-400",
        textColor: "text-cyan-400",
        delay: 0.8,
    },
    {
        id: 4,
        type: "YL-2",
        time: "6:00 - 7:00 PM",
        day: "Mon - Thu",
        ageGroup: "8 to 10 years",
        backgroundColor: "bg-red-400",
        textColor: "text-red-400",
        delay: 1.1,
    },
    {
        id: 5,
        type: "YL-3",
        time: "12:00 - 1:30 PM",
        day: "Sat & Sun",
        ageGroup: "9 to 11 years",
        backgroundColor: "bg-teal-400",
        textColor: "text-teal-400",
        delay: 1.4,
    },
    {
        id: 6,
        type: "YL-4",
        time: "7:00 - 8:00 PM",
        day: "Mon - Thu",
        ageGroup: "10 to 12 years",
        backgroundColor: "bg-cyan-400",
        textColor: "text-cyan-400",
        delay: 1.7,
    },
    {
        id: 7,
        type: "YL-5",
        time: "7:00 - 8:00 PM",
        day: "Mon - Thu",
        ageGroup: "11 to 13 years",
        backgroundColor: "bg-red-400",
        textColor: "text-red-400",
        delay: 2.0,
    },
    {
        id: 8,
        type: "YL-6",
        time: "10:00 - 11:30 AM",
        day: "Sat & Sun",
        ageGroup: "12 to 14 years",
        backgroundColor: "bg-teal-400",
        textColor: "text-teal-400",
        delay: 2.3,
    },
    {
        id: 9,
        type: "Teen-1",
        time: "6:30 - 7:30 AM",
        day: "Mon - Thu",
        ageGroup: "Abov 12 years",
        backgroundColor: "bg-cyan-400",
        textColor: "text-cyan-400",
        delay: 2.6,
    },
    {
        id: 10,
        type: "Teen-2",
        time: "6:30 - 7:00 AM",
        day: "Mon - Thu",
        ageGroup: "Above 12 years",
        backgroundColor: "bg-red-400",
        textColor: "text-red-400",
        delay: 2.9,
    },
    {
        id: 11,
        type: "Teen-3",
        time: "8:00 - 9:00 PM",
        day: "Mon - Thu",
        ageGroup: "Above 12 years",
        backgroundColor: "bg-teal-400",
        textColor: "text-teal-400",
        delay: 3.1,
    },
   

]